// Generated by Selenium IDE
require("chromedriver");
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("decibe", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("it", async function () {
    await driver.get("http://localhost:3000/");
    await driver.manage().window().setRect({ width: 900, height: 907 });
    await driver.findElement(By.id("fibonacciInput")).click();
    await driver.findElement(By.id("fibonacciInput")).sendKeys("1");
    await driver.findElement(By.id("fibonacciSubmit")).click();
    if (
      !(await driver.findElement(By.id("fibonacciResponse")).getText()) == "0"
    ) {
      throw console.error();
    } else {
      await driver.close();
    }
  }).timeout(100000);
});
